### ISSUE TITLE
No quest marker for The Neverending Duel

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/WoW-BugTracker#193]
**Game Version:**
> 8.0.1 Alpha Build 26141

**Description:**
> We don't know where to go to complete that quest

**Details:**
> There is nothing on the map to say where it is, and nothing in the quest text. Maybe that's intended because in the text it says "find"

**Logs, Images, Videos**
> https://i.imgur.com/kxMieGt.jpg

**Reproducible:**
> 100%

**Howto:**
> Have The neverending Duel

**Comment by Kutikuti** [comment]
Same for Wanted: Dazarian Empress

**Comment by Mystler** [comment]
Can confirm the issue. Fortunately, I saw the two dueling creatures during my explorations near the main road between Dazar'alor and the Temple of Rezan, before. I did not try to kill them because I did not have the quest and they had like >250k HP each, iirc. This makes we wonder if this quest is also supposed to be flagged as a Group quest?

**Comment by Kutikuti** [comment]
fixed in 26231
