### ISSUE TITLE
Risen Skulker from [All Will Serve] has a delay between casts

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#345]
**Game Version:**
> 8.0.1 Release Build 27366

**Description:**
> Risen Skulker from All Will Serve has a delay between casts

**Details:**
> Risen Skulker has a new delay between casts. 

**Logs, Images, Videos**
> Example of before August 8th vs afterward (seems to have happened in a hotfix early August 8th) https://media.discordapp.net/attachments/405268157440458753/477041673243852800/unknown.png?width=1044&height=170
>logs compared - https://www.warcraftlogs.com/reports/wAxRLMNjHtfVyFd2#fight=2&type=casts&source=44&view=events
>https://www.warcraftlogs.com/reports/cNw1Ytp3xjT6BGXJ#fight=2&type=casts&source=43&view=events
>Delay in game https://i.gyazo.com/3e6ecf6f5b1bb64d4e834c0a8eadf009.mp4

**Reproducible:**
> Yes

**Howto:**
> Summon Skulker and log casts with variable haste, compare with older logs of Skulker

**Comment by Melekus** [comment]
On further investigation of the last log, it seems that during Bloodlust, the interval is shortened to 1.2s because the cast finishes earlier.

My theory is that every 1.2s, the game checks if the Risen Skulker is casting or not. 
> If it's casting, it will just continue its cast and wait another 1.2s
> If it's not casting, it orders the guardian to start casting
This would explain the 1.2s interval observed during Bloodlust, as well as the 2.4s interval observed outside Bloodlust

**Comment by Chewsdaydk** [comment]
Problem in question is fixed, some odd behaviour persists but I think this counts as fixed.
