### ISSUE TITLE
Lichborne is a shapeshift effect and is cancelled by using Mounts/Soulshape etc

### ISSUE THREAD

**Issue by Chewsdaydk** [SimCMinMax/WoW-BugTracker#446]
**Game Version:**
> 9.0.1 beta Build 34324

**Description:**
> Lichborne counts as a shapeshift and prevents you from using anything on this list https://www.wowhead.com/spells?filter=31;2;0#0+20

**Logs, Images, Videos**
> https://i.gyazo.com/6693e62577434cf678ba4eb0bc839415.mp4

**Comment by BanterDK** [comment]
The tooltip does (and has, for BfA) state does allude to the fact that the player is transformed to be undead:
> Draw upon unholy and frost energies to become Undead for 10 sec. 

The coding implementation uses Shapeshift to achieve this affect. 

![9b366fcb03979b46bae0f76e3546bf45](https://user-images.githubusercontent.com/25447367/81705618-9306b000-94b2-11ea-9b6f-9b4d24dfa813.png)

Together, the tooltip/implementation seems to indicate that it is intentional, but also a possible oversight (especially in the case of Frostscythe).

**Comment by Chewsdaydk** [comment]
Just for clarity, The Lichborne I reported this bug about is actually https://shadowlands.wowhead.com/spell=49039/lichborne

The new baseline Lichborne and not the PvP talent. If the same bug exists with the PvP talent I think that should be a separate bug or tested specifically, I didn't check myself.

**Comment by Chewsdaydk** [comment]
No longer prevents casts of these things, but now when you cast them it removes Lichborne from you.

**Comment by Chewsdaydk** [comment]
fixed

**Comment by Chewsdaydk** [comment]
this is still cancelled by things like mounts, not sure what the threshold should be for working as intended so reopening for now

**Comment by Chewsdaydk** [comment]
fixed at some point
