### ISSUE TITLE
Slaughter Poison inconsistencies alongside standard poison

### ISSUE THREAD

**Issue by Mystler** [SimCMinMax/WoW-BugTracker#585]
**Game Version:**
> 9.0.1 beta Build 35755

**Description:**
> There are situations where Slaughter Poison can be up alongside Deadly or Instant Poison whereas otherwise it overrides them. Not totally sure on when this happens or what is even intended but it is very unintuitive. Feel free to comment with more details and example and reproduction cases.
Also, only auto attacks seem to trigger the poison for Sub and Outlaw.

**Comment by ashokmathur** [comment]
Am able to consistently reproduce this by not having any lethal poison up and then Slaughter out of subterfuge 2+ times in a row.

**Comment by Mystler** [comment]
Slaughter Poison only procs from auto attacks on Sub and Outlaw. Moving this in favor of closing the general #431.

**Comment by EvanMichaels** [comment]
Following up on @ashokmathur comment here, this still happens in the latest build.

Using Slaughter twice in a row from Subterfuge will apply Deadly Poison on the second cast of Slaughter instead of refreshing the duration of Slaughter Poison. This allows both to be up at the same time. (Although they are not fully both active since the Slaughter Poison DoT overwrites the Deadly Poison DoT.)

**Comment by Mystler** [comment]
Slaughter is gone. Closing.
